INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'reer', N'rerereer', N'', N'')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'rerere', N'rererer', N'', N'')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'erreererre', N'rereereer', N'', N'')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'טוהר ', N'??????', N'toharashk@gmail.com', N'123456789')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'טוהר', N'??????', N'toharashk@gmail.com', N'123456789')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'אושרי', N'??????', N'oshraioashk@gmail.com', N'122433')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'טוהר', N'??????', N'oshrikattoharashk@gmail.com', N'123123456456789789')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'שמשון', N'??????', N'shimshonhagibo1@gmail.com', N'???????????')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'אושרי', N'??????', N'oshrikatitohartziioungarua@gmail.com.thharbettah', N'1234556')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'אושרי', N'קטריבס', N'oshrikat@gmialiii.com', N'1234454')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'אושרי', N'????', N'computer@gmial.com', N'??????')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'דודי', N'????', N'duditet@gamil.com', N'123456')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'אושרי', N'??????', N' oshrikat@gmail.com', N'12112121')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'tohar', N'sddsds', N'123@gmail.com', N'sdssdsds')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'?????', N'??????', N'12121@?????????.?', N'124545')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'?????', N'??????', N'neymartheloser123@gmsil.com', N'123456')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'?????', N'??????', N'oshrikit@gmail.com ', N'122345667')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'אושרי', N'קטריבס', N'oshi/.rkat@ga', N'123456')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'turhd', N'ssdsdsds', N'dsdsds@fgdfdf.comcd', N'sdsdsdsdsdsd')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'??????', N'??????', N'????????', N'?@???.??')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'Eeyal Levi', N'Levi', N'1234567890', N'dudi@dudi.tetro.il')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'', N'', N'', N'')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'אודשרי', N'קכקכקכק', N'כגקכקככק.כג@', N'???????')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'אושרי', N'קטריבס', N'oshrikat@gmail.com', N'123456')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'אושרי', N'קטריבס', N'loyodea123@gmail.com', N'123456')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'אושרי ', N'קטריבס', N'oshri@gmail.coom', N'123456')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'אושריג', N'גכגכגגכ', N'גכגכ@דגכגד.בםצ', N'????????')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'גדגדגד', N'גדגדגדגדג', N'osheri@gmail.com', N'???????')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'אושרי', N'קטריבס', N'ohsirthebest@gmal.com', N'123456')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'', N'', N'', N'')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'אושרי', N'קטריבס', N'oshrithebest@gmaili.com', N'123456')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'אושרי', N'קטריבס', N'oshri@gmail.com', N'123455')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'אושרי', N'קטריבס', N'oshri@gmail.com', N'123455')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'אושרי', N'קטריבס', N'oshri@gmail.com', N'123455')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'אושרי', N'קטריבס', N'oshirkarff@gmial.com', N'121212121')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'אושרי', N'קטריבס', N'oshirkarff@gmial.com', N'121212121')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'אושרי', N'??????', N'1234@??????.??????', N'123545564')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'אושרי', N'??????', N'1234@??????.??????', N'123545564')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'אושרי', N'??????', N'1234@??????.??????', N'123545564')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'אושרי', N'??????', N'1234@??????.??????', N'123545564')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'אושרי', N'??????', N'1234@??????.??????', N'123545564')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'אושרי', N'??????', N'oshrikati@gmiakl;d/.cxds', N'122121??')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'אושרי', N'??????', N'oshrikati@gmiakl;d/.cxds', N'122121??')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'אושרי', N'??????', N'oshrikati@gmiakl;d/.cxds', N'122121??')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'אושרי', N'??????', N'oshrikati@gmiakl;d/.cxds', N'122121??')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'אושרי', N'??????', N'oshrikati@gmiakl;d/.cxds', N'122121??')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'אושרי', N'??????', N'oshrikati@gmiakl;d/.cxds', N'122121??')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'אושרי', N'??????', N'oshrikati@gmiakl;d/.cxds', N'122121??')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'אושרי', N'??????', N'oshrikati@gmiakl;d/.cxds', N'122121??')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'אושרי', N'??????', N'oshrikati@gmiakl;d/.cxds', N'122121??')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'אושרי', N'??????', N'oshrikati@gmiakl;d/.cxds', N'122121??')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'אושרי', N'קטריבס', N'oshirkarff@gmial.com', N'121212121')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'tova', N'abekasis', N'1q2w3e4r', N'tiva@tetro.pro.co.il')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'oshro', N'koto', N'123456', N'oshrikoto@gmail.com')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'daniel', N'danielo', N'daniel123', N'daniel@gmail.com')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'trtr', N'ffdfdfdf', N'dfddfdf', N'dfdfd@fdfd.fdfd')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'ido', N'ghjgjj', N'12345', N'ido@gmail.com')
INSERT INTO [dbo].[RegisterData] ([firstname], [lastname], [pass], [email]) VALUES (N'oshri', N'adjo', N'dsdjsdo', N'jodwjsodw@d.dsf')
