//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Giluah_Kehalaha___NEW_WEBSITE_2022
{


    public partial class RegisterPage
    {
    }
}
